model:
  backbone2d:
    model_name: "resnet18"
    in_channels: 3
    out_features: 64
  backbone3d:
    model_name: "swin_t"  # Using Swin Transformer Tiny for 3D backbone.
    in_channels: 3
    out_features: 64
  fusion:
    fusion_out_channels: 128
  segmentation:
    segmentation_out_channels: 1  # One channel per object mask (binary per channel).

training:
  batch_size: 4
  epochs: 10
  learning_rate: 0.001
  optimizer: "adam"
  scheduler:
    type: "StepLR"
    step_size: 5
    gamma: 0.1
