# NOTE: input_channels_order in backbones must match model type
#       It is used for reshaping the input data.

# NOTE: For head_config layers, set "in_channels" to null for the first layer.
#       This value will be dynamically determined and replaced at runtime based
#       on the output channels of the preceding module. Do not manually specify
#       a value here.

# NOTE: "model:backbone2d/3d:type: has to match (case-sensitive) the name of
#        weights in torchvision.models (ResNet18_Weights) excluding the
#        "_Weights" suffix.

model:
  backbone2d:
    type: "ResNet18"
    input_channels_order: "chw"
    pretrained: true
    freeze_backbone: false
    remove_head: true
    head_config:
      layers:
        - type: "Conv2d"
          in_channels: null
          out_channels: 64
          kernel_size: 1
          stride: 1
          padding: 0

  backbone3d:
    type: "ResNet18"
    input_channels_order: "chw"
    pretrained: true
    freeze_backbone: false
    remove_head: true
    head_config:
      layers:
        - type: "Conv2d"
          in_channels: null
          out_channels: 64
          kernel_size: 1
          stride: 1
          padding: 0

  fusion:
    head_config:
      layers:
        - type: "Conv2d"
          in_channels: null
          out_channels: 128
          kernel_size: 3
          stride: 1
          padding: 1
        - type: "ReLU"

  segmentation:
    head_config:
      layers:
        - type: "Conv2d"
          in_channels: null
          out_channels: 1
          kernel_size: 3
          stride: 1
          padding: 1
        - type: "ReLU"
        - type: "Conv2d"
          in_channels: 1
          out_channels: 1
          kernel_size: 1
          stride: 1
          padding: 0

loss:
  type: "BCEWithLogitsLoss"
  reduction: "mean"

training:
  batch_size: 1
  epochs: 1

optimizer:
  type: "Adam"
  lr: 0.001
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1e-08

scheduler:
  type: "StepLR"
  step_size: 5
  gamma: 0.1
