# NOTE: input_channels_order in backbones must match model type
#       It is used for reshaping the input data.

# NOTE: "models:branches:rgb/pc:backbone:model_name: has to match
#        (case-sensitive) the name of weights in torchvision.models
#        (ResNet18_Weights) excluding the "_Weights" suffix.

models:
  branches:
    rgb:
      input_channels_order: "chw"

      backbone:
        model_name: "ResNet18"
        sub_module: ""
        pretrained: true
        freeze_backbone: false
        remove_head: true

      head_layers:
        - type: "ConvTranspose2d"
          out_channels: 256
          kernel_size: 4
          stride: 2
          padding: 1
        - type: "ConvTranspose2d"
          out_channels: 128
          kernel_size: 4
          stride: 2
          padding: 1

    pc:
      input_channels_order: "chw"

      backbone:
        model_name: "ResNet18"
        sub_module: ""
        pretrained: true
        freeze_backbone: false
        remove_head: true

      head_layers:
        - type: "ConvTranspose2d"
          out_channels: 256
          kernel_size: 4
          stride: 2
          padding: 1
        - type: "ConvTranspose2d"
          out_channels: 128
          kernel_size: 4
          stride: 2
          padding: 1

  fusion:
    head_layers:
      - type: "Conv2d"
        out_channels: 128
        kernel_size: 3
        stride: 1
        padding: 1
      - type: "ReLU"
      - type: "Conv2d"
        out_channels: 128
        kernel_size: 3
        stride: 1
        padding: 1
      - type: "ReLU"

  predictor:
    head_layers:
      - type: "ConvTranspose2d"
        out_channels: 128
        kernel_size: 4
        stride: 2
        padding: 1
      - type: "ReLU"
      - type: "ConvTranspose2d"
        out_channels: 64
        kernel_size: 4
        stride: 2
        padding: 1
      - type: "ReLU"
      - type: "ConvTranspose2d"
        out_channels: 32
        kernel_size: 4
        stride: 2
        padding: 1
      - type: "ReLU"
      - type: "ConvTranspose2d"
        out_channels: 16
        kernel_size: 4
        stride: 2
        padding: 1
      - type: "ReLU"
      - type: "ConvTranspose2d"
        out_channels: 8
        kernel_size: 4
        stride: 2
        padding: 1
loss:
  type: "BCEWithLogitsLoss"
  reduction: "mean"

training:
  batch_size: 1
  epochs: 1

optimizer:
  type: "Adam"
  lr: 0.001
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1e-08

scheduler:
  type: "StepLR"
  step_size: 5
  gamma: 0.1
