model:
  backbone2d:
    type: "resnet18"
    in_channels: 3
    out_channels: 64
    pretrained: True
  backbone3d:
    type: "swin_t"  # Using Swin Transformer Tiny for 3D backbone.
    in_channels: 3
    out_channels: 64
    pretrained: True
  fusion:
    out_channels: 128
  segmentation:
    out_channels: 1  # One channel per object mask (binary per channel).

loss:
  type: "BCEWithLogitsLoss" # BCEWithLogitsLoss for per-channel binary segmentation
  reduction: "mean"

training:
  batch_size: 4
  epochs: 10

optimizer:
  type: "Adam"
  lr: 0.001
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1e-08

scheduler:
  type: "StepLR"
  step_size: 5
  gamma: 0.1
